#!/bin/sh

APP_NAME=$1
SCRIPT_NAME=$(basename $0)
TEMPLATE="$(cd $(dirname $0) && pwd)/base.rb"

# Check for given application name
if [ -z $APP_NAME ]; then
  echo 'An application name should be given as first argument.' 
  echo 'Usage:'
  echo "  $SCRIPT_NAME APP_NAME"
  exit 1
fi

# Check if application's directory already exists
if [ -d "$APP_NAME" ]; then
  echo "Directory $APP_NAME already exists. Aborting!"
  exit 1
fi

# Prepare the application directory
echo -n 'Creating application directory...'
mkdir $APP_NAME
cd $APP_NAME
echo ' done!'
echo -n 'Writing a sample Gemfile...'
cat >Gemfile <<EOL
source 'https://rubygems.org'

gem 'rails', '3.2.8'
EOL
echo ' done!'

# Install rails in the application directory
echo -n 'Running bundle install...'
bundle install --path vendor/bundle >/dev/null
echo ' done!'

# Generate a new rails application
echo 'Creating new rails application'
bundle exec rails new . -d postgresql -T -f --skip-bundle -m $TEMPLATE
